### ISSUE TITLE
[Linux] what are the dependencies for ParTool?

### ISSUE THREAD

**Issue by MartinF99** [Kaplas80/ParManager#12]
What are the dependencies for using ParTool on linux? I always get a backtrace:
`Process terminated. Couldn't find a valid ICU package installed on the system. Set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode.GetGlobalizationInvariantMode()
   at System.Globalization.GlobalizationMode..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_InvariantCulture()
   at CommandLine.ParserSettings..ctor()
   at CommandLine.Parser..ctor(System.Action`1<CommandLine.ParserSettings>)
   at ParTool.Program.Main(System.String[])
Abgebrochen
`

**Comment by Kaplas80** [comment]
It only needs .NET Core 3.1 runtime. What distro are you using?

**Comment by MartinF99** [comment]
siduction, a debian sid derivative. I have mono installed and libicu (which mono uses to get icu information) is also installed.

**Comment by Kaplas80** [comment]
I don't have that distro, but I've tried with a clean Debian 12 installation and it throws the same error. I've been able to run the app  using `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 ./ParTool`
