### ISSUE TITLE
Can't unpack Like A Dragon 8 Demo db.elvis.trial.zhs.par

### ISSUE THREAD

**Issue by Coconutat** [Kaplas80/ParManager#14]
Use ParTool in Powershell report this:
```
Copyright (c) 2021 Kaplas

Unhandled exception. System.FormatException: PARC: Bad magic Id.
   at ParLibrary.Converter.ParArchiveReader.Convert(BinaryFormat source)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute2[T0,T1,TRet](CallSite site, T0 arg0, T1 arg1)
   at Yarhl.FileFormat.ConvertFormat.With(IConverter converter, Object src)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute3[T0,T1,T2,TRet](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Yarhl.FileFormat.ConvertFormat.With[TConv,TParam](TParam param, Object src)
   at Yarhl.FileSystem.Node.TransformWith[TConv,TParam](TParam param)
   at ParTool.Program.Extract(Extract opts)
   at ParTool.Program.<>c__DisplayClass2_0.<Main>b__1(IEnumerable`1 x)
   at CommandLine.ParserResultExtensions.WithNotParsed[T](ParserResult`1 result, Action`1 action)
   at ParTool.Program.Main(String[] args)
```

**Comment by Coconutat** [comment]
If you need db.elvis.trial.zhs.par,this file in here:
[db.elvis.trial.zhs.zip](https://github.com/Kaplas80/ParManager/files/13335175/db.elvis.trial.zhs.zip)

**Comment by Kaplas80** [comment]
`PARC: Bad magic Id.` indicates that it isn't a PAR file.

They have done it before: sometimes they use `.par` extension for files that aren't PAR files. Or maybe it has some encryption.

**Comment by Coconutat** [comment]
> `PARC: Bad magic Id.` indicates that it isn't a PAR file.
> 
> They have done it before: sometimes they use `.par` extension for files that aren't PAR files. Or maybe it has some encryption.

Yes, I think they have encrypted it. It may be due to fear that the trial version may lead to the official version of the game being cracked.Thank you for your help. Let's wait for the official version.
